#!/usr/bin/env bash
# Twenty CRM Security Audit — Environment Setup
# Idempotent: safe to run multiple times.
#
# Pinned hashes:
#   Repo commit:   fc90b4ba8bb0a5d7c12c846fe9b2305527a0f7a8
#   Server image:  twentycrm/twenty@sha256:fd6faa713fd2042d5d87e5705d47d24e492fc5202e7394e188f438085b483fad
#   DB image:      postgres:16@sha256:4b7183ac05f8ef417db21fd72d71047a4238340c261d3cc3ddb6d579ab5071ae
#   Redis image:   redis:7-alpine@sha256:6ab0b6e7381779332f97b8ca76193e45b0756f38d4c0dcda72dbb3c32061ab99
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET_BASE_URL="${TARGET_BASE_URL:-http://172.20.0.4:3000}"
DOCKER_NETWORK="twenty-audit-net"

echo "============================================================"
echo " Twenty CRM Security Audit Setup"
echo "============================================================"
echo " Repo commit : fc90b4ba8bb0a5d7c12c846fe9b2305527a0f7a8"
echo " Server image: twentycrm/twenty@sha256:fd6faa713fd2042d5d87e5705d47d24e492fc5202e7394e188f438085b483fad"
echo " DB image    : postgres:16@sha256:4b7183ac05f8ef417db21fd72d71047a4238340c261d3cc3ddb6d579ab5071ae"
echo " Redis image : redis:7-alpine@sha256:6ab0b6e7381779332f97b8ca76193e45b0756f38d4c0dcda72dbb3c32061ab99"
echo " Target URL  : ${TARGET_BASE_URL}"
echo "============================================================"

# -------------------------------------------------------------------------
# 1. Create evidence directory
# -------------------------------------------------------------------------
mkdir -p "${SCRIPT_DIR}/evidence"
touch "${SCRIPT_DIR}/evidence/.gitkeep"
echo "[+] Evidence directory ready: ${SCRIPT_DIR}/evidence"

# -------------------------------------------------------------------------
# 2. Verify python3 is available
# -------------------------------------------------------------------------
if ! command -v python3 &>/dev/null; then
    echo "[!] FATAL: python3 not found. Install python3 and retry." >&2
    exit 1
fi
PY_VERSION="$(python3 --version 2>&1)"
echo "[+] Python: ${PY_VERSION}"

# -------------------------------------------------------------------------
# 3. Write config.env (idempotent — preserves existing values)
# -------------------------------------------------------------------------
CONFIG_FILE="${SCRIPT_DIR}/config.env"
if [[ ! -f "${CONFIG_FILE}" ]]; then
    cat > "${CONFIG_FILE}" <<EOF
# Twenty CRM Audit Configuration
# Generated by setup.sh — edit as needed
TARGET_BASE_URL=${TARGET_BASE_URL}
EOF
    echo "[+] config.env written: ${CONFIG_FILE}"
else
    echo "[+] config.env already exists (preserved): ${CONFIG_FILE}"
fi

# -------------------------------------------------------------------------
# 4. Verify connectivity to target; connect to docker network if needed
# -------------------------------------------------------------------------
check_connectivity() {
    # Try both /healthz and / since the healthcheck endpoint may vary
    if curl -fsS --max-time 5 "${TARGET_BASE_URL}/healthz" &>/dev/null; then
        return 0
    fi
    if curl -fsS --max-time 5 "${TARGET_BASE_URL}/" &>/dev/null; then
        return 0
    fi
    # Try graphql endpoint (always present)
    if curl -fsS --max-time 5 -X POST "${TARGET_BASE_URL}/graphql" \
        -H 'Content-Type: application/json' \
        -d '{"query":"{ __typename }"}' &>/dev/null; then
        return 0
    fi
    return 1
}

echo "[*] Checking connectivity to ${TARGET_BASE_URL}..."
if check_connectivity; then
    echo "[+] Target is reachable."
else
    echo "[!] Target not reachable. Attempting docker network connect..."
    SELF_HOSTNAME="$(hostname)"
    if command -v docker &>/dev/null; then
        if docker network connect "${DOCKER_NETWORK}" "${SELF_HOSTNAME}" 2>&1; then
            echo "[+] Connected to ${DOCKER_NETWORK}."
            sleep 1
            if check_connectivity; then
                echo "[+] Target now reachable after network connect."
            else
                echo "[!] WARNING: Still cannot reach ${TARGET_BASE_URL} after network connect." >&2
                echo "    Verify the audit-twenty-server container is running and on ${DOCKER_NETWORK}." >&2
            fi
        else
            echo "[!] WARNING: docker network connect failed (may already be connected)." >&2
            echo "    If running outside Docker, ensure ${TARGET_BASE_URL} is routable." >&2
        fi
    else
        echo "[!] WARNING: docker command not available." >&2
        echo "    Manually ensure the reviewer container is on network ${DOCKER_NETWORK}:" >&2
        echo "      docker network connect ${DOCKER_NETWORK} \$(hostname)" >&2
        echo "    Then re-run setup.sh." >&2
    fi
fi

echo ""
echo "[+] Setup complete. Run: bash run_all_exploits.sh"
